---
ahoyapi: v2

commands:
  up:
    usage: Build project.
    cmd: docker-compose up -d "$@"

  down:
    usage: Delete project.
    cmd: docker-compose down

  build:
    usage: Build project.
    cmd: docker-compose up -d --build "$@"

  cli:
    usage: Start a shell inside TEST container.
    cmd: docker-compose exec -T test bash

  run:
    usage: Run command inside TEST container.
    cmd: docker-compose exec -T test bash -c "$@"

  drush:
    usage: Run drush commands in TEST container.
    cmd: docker-compose exec -T test drush "$@"

  logs:
    usage: Show Docker logs.
    cmd: docker-compose logs "$@"

  ps:
    usage: List running Docker containers.
    cmd: docker-compose ps

  restart:
    usage: Restart Docker containers.
    cmd: docker-compose restart

  stop:
    usage: Stop Docker containers.
    cmd: docker-compose stop "$@"

  install:
    usage: Install the profile.
    cmd: docker-compose exec -T test drush si -y govcms "$@"

  login:
    usage: Login to a website.
    cmd: docker-compose exec -T test drush uli "$@"

  cex:
    usage: Export site configuration to default location.
    cmd: docker-compose exec -T test drush cex sync

  cim:
    usage: Import site configuration. Will perform partial configuration overrides if a parameter is provided.
    cmd: |
      if [ -f ./config/default/system.site.yml ]; then
        configUuid="$(cat ./config/default/system.site.yml | grep uuid | tail -c +7 | head -c 36)"
        docker-compose exec -T test drush config-set system.site uuid $configUuid
      fi

      # No support for config import for entire site install.
      docker-compose exec -T test drush ev '\Drupal::entityManager()->getStorage("shortcut_set")->load("default")->delete();'
      docker-compose exec -T test drush pm-uninstall shortcut

      if [ "$#" -eq 0 ]
        then
          docker-compose exec -T test drush cim sync
      else
          docker-compose exec -T test drush cim "$@" --partial
      fi

  lint:
    usage: Lint code
    cmd: docker-compose exec -T test lint-theme

  test-behat:
    usage: Run Behat tests.
    cmd: docker-compose exec -T test behat "$@"

  test-phpunit:
    usage: Run PHPUnit tests.
    cmd: docker-compose exec -T test phpunit "$@"

  pull:
    usage: Pull latest docker images.
    cmd: docker image ls --format \"{{.Repository}}:{{.Tag}}\" | grep govcms8lagoon/ | grep -v none | xargs -n1 docker pull | cat

  audit-site:
    usage: Run site audit
    cmd: docker-compose exec -T test drutiny profile:run ci @self "$@"
