name: PR assignment

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 'Auto-assign PR'
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: steveworley,yusufhm
          numOfAssignee: 1
